package eu.transittrack.schedule.optimize.model

import java.time.Instant
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.LockModeType
import jakarta.persistence.SequenceGenerator
import jakarta.persistence.Table

import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Lock
import org.springframework.data.jpa.repository.Query
import org.springframework.data.repository.query.Param

enum class OptimizationRunState { QUEUED, RUNNING, SUCCEEDED, FAILED }

enum class OptimizationRecommendationKind { STOP_TIME, TRIP_SHIFT }

enum class OptimizationRecommendationStatus { PENDING, SELECTED, APPLIED, DISMISSED, UNAVAILABLE }

/**
 * One asynchronous analysis request. `feedId`/`revisionId` freeze the feed's ACTIVE revision at
 * submission time — see [eu.transittrack.schedule.optimize.ScheduleOptimizationService]; a run is
 * never translated to a later revision even if one is activated while it is `QUEUED`/`RUNNING`.
 * Filter fields are the full normalized request inputs (all optional besides the feed/observed
 * window/minimum-sample count, enforced by
 * [eu.transittrack.schedule.optimize.OptimizationRunRequest]).
 */
@Entity
@Table(name = "schedule_optimization_run")
class OptimizationRunRow(
    @Column(name = "feed_id", nullable = false) var feedId: Long,
    @Column(name = "revision_id", nullable = false) var revisionId: Long,
    @Column(name = "service_id") var serviceId: String? = null,
    @Column(name = "route_id") var routeId: String? = null,
    @Column(name = "direction_id") var directionId: Int? = null,
    @Column(name = "window_from_sec") var windowFromSec: Int? = null,
    @Column(name = "window_to_sec") var windowToSec: Int? = null,
    @Column(name = "observed_from", nullable = false) var observedFrom: Instant,
    @Column(name = "observed_to", nullable = false) var observedTo: Instant,
    @Column(name = "minimum_samples", nullable = false) var minimumSamples: Int,
    @Enumerated(EnumType.STRING) @Column(nullable = false) var state: OptimizationRunState = OptimizationRunState.QUEUED,
    @Column(name = "started_at") var startedAt: Instant? = null,
    @Column(name = "completed_at") var completedAt: Instant? = null,
    @Column var error: String? = null,
    @Column(name = "created_at", nullable = false) var createdAt: Instant = Instant.now(),
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "scheduleOptimizationRunSeq")
    @SequenceGenerator(name = "scheduleOptimizationRunSeq", sequenceName = "schedule_optimization_run_seq", allocationSize = 50)
    var id: Long? = null,
)

interface OptimizationRunRepository : JpaRepository<OptimizationRunRow, Long> {
    /**
     * Bounded, newest-first page of runs for one feed — backs the UI's runs-history list.
     * A native query (matching `OptimizationRecommendationRepository.page`'s pattern) so an
     * arbitrary `offset`/`limit` pair maps directly to `OFFSET`/`LIMIT`.
     */
    @Query(
        value = "select * from schedule_optimization_run where feed_id = :feedId order by created_at desc offset :offset limit :limit",
        nativeQuery = true,
    )
    fun page(
        @Param("feedId") feedId: Long,
        @Param("offset") offset: Int,
        @Param("limit") limit: Int,
    ): List<OptimizationRunRow>
}

/**
 * A persistent, reviewable proposed edit generated by exactly one run. `currentValue`,
 * `proposedValue`, and `evidence` are JSONB (see [org.hibernate.annotations.JdbcTypeCode] usage
 * elsewhere in this codebase, e.g. `eu.transittrack.gtfs.draft.DraftEdit`) so future analysis
 * versions can enrich explanations without a migration; `sampleCount`/`deltaSec` stay strongly
 * typed columns because they are queried/aggregated directly. `conflictKey` identifies edits that
 * cannot safely coexist at apply time (Task 5).
 */
@Entity
@Table(name = "schedule_optimization_recommendation")
class OptimizationRecommendationRow(
    @Column(name = "run_id", nullable = false) var runId: Long,
    @Enumerated(EnumType.STRING) @Column(nullable = false) var kind: OptimizationRecommendationKind,
    @Column(name = "sample_count", nullable = false) var sampleCount: Int,
    @Column(name = "delta_sec", nullable = false) var deltaSec: Int,
    @Column(nullable = false) var reason: String,
    @Enumerated(EnumType.STRING) @Column(nullable = false)
    var status: OptimizationRecommendationStatus = OptimizationRecommendationStatus.PENDING,
    @JdbcTypeCode(SqlTypes.JSON) @Column(name = "current_value") var currentValue: String? = null,
    @JdbcTypeCode(SqlTypes.JSON) @Column(name = "proposed_value") var proposedValue: String? = null,
    @JdbcTypeCode(SqlTypes.JSON) @Column var evidence: String? = null,
    @Column(name = "conflict_key") var conflictKey: String? = null,
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "scheduleOptimizationRecommendationSeq")
    @SequenceGenerator(
        name = "scheduleOptimizationRecommendationSeq",
        sequenceName = "schedule_optimization_recommendation_seq",
        allocationSize = 50,
    )
    var id: Long? = null,
)

interface OptimizationRecommendationRepository : JpaRepository<OptimizationRecommendationRow, Long> {
    /**
     * Row-locking read for `ScheduleOptimizationService.apply`: a `PESSIMISTIC_WRITE` lock on every
     * selected recommendation row so two concurrent `apply` calls whose recommendation-id sets
     * overlap serialize on the shared rows, turning the `PENDING`-status check that follows into a
     * true compare-and-swap rather than a TOCTOU race that could fork two drafts from one selection.
     * Disjoint selections (no shared row) still proceed concurrently — this locks the individual
     * recommendation rows, not the whole run. Modeled on
     * [eu.transittrack.gtfs.revision.GtfsRevisionRepository.findByIdForUpdate].
     */
    @Lock(LockModeType.PESSIMISTIC_WRITE)
    @Query("select r from OptimizationRecommendationRow r where r.id in :ids")
    fun findAllByIdForUpdate(ids: Collection<Long>): List<OptimizationRecommendationRow>

    /**
     * Stable `(run_id, status, id)` pagination for `ScheduleOptimizationService.listRecommendations`.
     * A native query (rather than a `Pageable`-based derived query) so an arbitrary `offset`/`limit`
     * pair maps directly to `OFFSET`/`LIMIT` instead of being constrained to page-aligned windows.
     */
    @Query(
        value =
            "select * from schedule_optimization_recommendation " +
                "where run_id = :runId and (:status is null or status = :status) " +
                "order by status, id " +
                "offset :offset limit :limit",
        nativeQuery = true,
    )
    fun page(
        @Param("runId") runId: Long,
        @Param("status") status: String?,
        @Param("offset") offset: Int,
        @Param("limit") limit: Int,
    ): List<OptimizationRecommendationRow>
}
