{{- if .Values.roles.api.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lens.fullname" . }}-api
  labels:
    {{- include "lens.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "lens.fullname" . }}
    lens.role: api
  ports:
    - port: {{ .Values.roles.api.service.port }}
      targetPort: 8080
{{- end }}
