// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  // Generated by graphql-codegen — checked in, not hand-written; not our style rules to enforce.
  ignores: ['generated/**'],
})
